/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}"
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Quicksand', 'ui-sans-serif', 'system-ui'],
      },
      colors: {
        primary: {
          50:  '#F6F9FE',
          100: '#D2E3FF',
          500: '#1C65DA',
        },
        accent: {
          red: '#D9206E',
          green: '#079455',
          yellow: '#FDB022',
        },
        gray: {
          50:  '#FDFDFD',
          100: '#FAFAFA',
          200: '#F5F5F5',
          300: '#E9EAEB',
          400: '#D5D7DA',
          500: '#A4A7AE',
          600: '#717680',
          700: '#535862',
          800: '#414651',
          900: '#252B37',
          950: '#181D27',
          1000: '#0A0D12',
        },
      },
      borderRadius: {
        none: '0px',
        xxs: '2px',
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '10px',
        xl: '12px',
        '2xl': '16px',
        '3xl': '20px',
        '4xl': '24px',
        full: '9999px',
      },
      spacing: {
        xxs: '2px',
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        '3xl': '24px',
        '4xl': '32px',
        '5xl': '40px',
        '6xl': '48px',
        '7xl': '64px',
        '8xl': '80px',
        '9xl': '96px',
        '10xl': '128px',
        '11xl': '140px',
      },
      fontSize: {
        'display-3xl': ['3.75rem', { lineHeight: '4.5rem' }],
        'display-2xl': ['3rem', { lineHeight: '3.75rem' }],
        'display-xl': ['2.5rem', { lineHeight: '3rem' }],
        'display-lg': ['2.25rem', { lineHeight: '2.75rem' }],
        'display-md': ['2rem', { lineHeight: '2.5rem' }],
        'display-sm': ['1.75rem', { lineHeight: '2.375rem' }],
        'display-xs': ['1.5rem', { lineHeight: '2.25rem' }],
        'text-xl': ['1.25rem', { lineHeight: '2.125rem' }],
        'text-lg': ['1.125rem', { lineHeight: '2rem' }],
        'text-md': ['1rem', { lineHeight: '1.875rem' }],
        'text-sm': ['0.875rem', { lineHeight: '1.75rem' }],
        'text-xs': ['0.75rem', { lineHeight: '1.5rem' }],
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
    require("@tailwindcss/aspect-ratio"),
  ],
}